source 'https://github.com/CocoaPods/Specs.git'

target 'dvSection8_Example' do
  platform :ios, '9.0'
  use_frameworks!
  pod 'dvSection8', :path => '../'

  pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
  end

  target 'dvSection8_Tests' do
    inherit! :search_paths
  end
end
